# Cloud Run service configuration
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: tally-backend
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cpu-throttling: "true"
        run.googleapis.com/execution-environment: gen2
    spec:
      containerConcurrency: 1000
      timeoutSeconds: 300
      containers:
      - image: gcr.io/accountancy-469917/tally-backend:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: SERVE_CLIENT
          value: "false"
        # Database and OAuth config are sourced from Secret Manager at runtime
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: DATABASE_URL
              key: latest
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: GOOGLE_CLIENT_ID
              key: latest
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: GOOGLE_CLIENT_SECRET
              key: latest
        - name: FRONTEND_ORIGIN
          valueFrom:
            secretKeyRef:
              name: FRONTEND_ORIGIN
              key: latest
        resources:
          limits:
            cpu: "1000m"
            memory: "1Gi"
          requests:
            cpu: "100m"
            memory: "256Mi"
  traffic:
  - percent: 100
    latestRevision: true
