// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://khohfpezhspasjertpgi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtob2hmcGV6aHNwYXNqZXJ0cGdpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyOTEzMDAsImV4cCI6MjA2OTg2NzMwMH0.lhqzEuHDLEx__UGaufy2vJCNyIqwfTDSZ9ERHT8nTLI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});